import { useState, useEffect, useRef, useCallback } from "react";
import { ThemeIntelData } from "@/hooks/useThemeIntelligence";
import { Skeleton } from "@/components/ui/skeleton";
import { RefreshCw, AlertTriangle, Newspaper, ExternalLink } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import WeeklyReportsSection from "./WeeklyReportsSection";
import VolumeDryUpSection from "./VolumeDryUpSection";
import { useVolumeDryUp } from "@/hooks/useVolumeDryUp";
import { calculateDispersion, getDispersionLabel, getDispersionShortLabel } from "@/hooks/useDispersion";
import { useSpyBenchmark } from "@/hooks/useSpyBenchmark";
import { useThemeNews, NewsArticle } from "@/hooks/useThemeNews";

const DM_MONO = "'DM Mono', monospace";
const COOLDOWN_MS = 30_000;
const STALE_HOURS = 4;

interface NarrativeState {
  text: string;
  generatedAt: string;
  themeCount: number;
}

function TopBottomCard({
  title,
  themes,
  color,
}: {
  title: string;
  themes: ThemeIntelData[];
  color: "teal" | "amber";
}) {
  const accent = color === "teal" ? "#00f5c4" : "#f5a623";
  return (
    <div
      className="rounded-lg p-4"
      style={{
        background: "rgba(255,255,255,0.04)",
        border: "1px solid rgba(255,255,255,0.08)",
        backdropFilter: "blur(12px)",
      }}
    >
      <h4
        className="font-['Syne',sans-serif] text-xs font-semibold uppercase tracking-widest mb-3"
        style={{ color: accent }}
      >
        {title}
      </h4>
      <div className="space-y-2.5">
        {themes.map((t, i) => (
          <div key={t.themeId} className="flex items-center gap-3">
            <span
              className="w-5 text-right text-xs text-muted-foreground"
              style={{ fontFamily: DM_MONO }}
            >
              {i + 1}
            </span>
            <div className="flex-1 min-w-0">
              <div className="flex items-center justify-between gap-2">
                <span className="font-['Syne',sans-serif] text-[13px] font-medium text-foreground truncate">
                  {t.themeName}
                </span>
                <span
                  className={`shrink-0 text-xs ${t.perf_1d >= 0 ? "text-[#00f5c4]" : "text-[#f5a623]"}`}
                  style={{ fontFamily: DM_MONO }}
                >
                  {t.perf_1d >= 0 ? "+" : ""}
                  {t.perf_1d.toFixed(2)}%
                </span>
              </div>
              <div className="mt-1 h-1 w-full overflow-hidden rounded-full bg-[rgba(255,255,255,0.06)]">
                <div
                  className="h-full rounded-full transition-all duration-700"
                  style={{
                    width: `${t.momentumScore}%`,
                    backgroundColor: accent,
                    opacity: 0.7,
                  }}
                />
              </div>
            </div>
            <span
              className="w-7 text-right text-[10px] text-muted-foreground"
              style={{ fontFamily: DM_MONO }}
            >
              {t.momentumScore}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

export default function InsightsTab({
  themes,
  accelerating,
  fading,
  isLoading: dataLoading,
  onOpenNewsPanel,
}: {
  themes: ThemeIntelData[];
  accelerating: ThemeIntelData[];
  fading: ThemeIntelData[];
  isLoading: boolean;
  onOpenNewsPanel?: (themeName: string) => void;
}) {
  const { dryUpThemes } = useVolumeDryUp();
  const { spy } = useSpyBenchmark();
  const { fetchMarketNews, marketNews, getAiSummary, getThemeSentiment, aiSummaries } = useThemeNews();
  const [marketSummary, setMarketSummary] = useState<string | null>(null);
  const [marketSummaryLoading, setMarketSummaryLoading] = useState(false);
  const [narrative, setNarrative] = useState<NarrativeState | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [cooldownEnd, setCooldownEnd] = useState(0);
  const [now, setNow] = useState(Date.now());
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    const id = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(id);
  }, []);

  // Fetch market news lazily when Insights tab renders
  useEffect(() => {
    fetchMarketNews();
  }, [fetchMarketNews]);

  const isCoolingDown = now < cooldownEnd;
  const cooldownSecs = Math.ceil((cooldownEnd - now) / 1000);

  const top5 = themes.slice(0, 5);
  const bottom5 = [...themes].sort((a, b) => a.momentumScore - b.momentumScore).slice(0, 5);

  const generateNarrative = useCallback(async () => {
    if (themes.length === 0 || isGenerating) return;

    const previousNarrative = narrative;
    setNarrative(null);
    setIsGenerating(true);

    try {
      const mapTheme = (t: ThemeIntelData) => {
        const validTickers = t.tickers.filter(tk => tk.status === "done");
        return {
          name: t.themeName,
          score: t.momentumScore,
          perf_1d: t.perf_1d,
          perf_1w: t.perf_1w,
          perf_1m: t.perf_1m,
          breadth: `${t.breadthUp}/${t.breadthTotal}`,
          advancing: t.breadthUp,
          declining: t.breadthTotal - t.breadthUp,
          // Volume data
          avgRelVol: t.avgRelVol,
          sustainedVol: t.sustainedVol !== null ? `${t.sustainedVol >= 0 ? "+" : ""}${t.sustainedVol.toFixed(0)}%` : null,
          volumeSpike: t.volumeSpikingUp > 0
            ? `${t.volumeSpikingUp}/${t.breadthTotal} spiking`
            : null,
          tickers: validTickers.map(tk => ({
            symbol: tk.symbol,
            perf_1d: tk.perf_1d,
          })),
        };
      };

      const top8 = themes.slice(0, 8).map(mapTheme);
      const bottom8 = [...themes].sort((a, b) => a.momentumScore - b.momentumScore).slice(0, 8).map(mapTheme);

      const outlierThemes = themes
        .filter(t => {
          if (t.perf_1d >= 1) return false;
          const validTickers = t.tickers.filter(tk => tk.status === "done");
          return validTickers.some(tk => tk.perf_1d > 5);
        })
        .slice(0, 5)
        .map(mapTheme);

      // Enrich with volume dry-up data
      const dryUpSet = new Set(dryUpThemes.map(d => d.themeName));
      const enrichWithDryUp = (t: any, original: ThemeIntelData) => {
        const dryUp = dryUpThemes.find(d => d.themeName === original.themeName);
        return {
          ...t,
          volumeDryUp: dryUpSet.has(original.themeName),
          sustainedVolChange: dryUp ? dryUp.change : null,
        };
      };

      const top8Enriched = top8.map((t, i) => enrichWithDryUp(t, themes.slice(0, 8)[i]));
      const bottom8Enriched = bottom8.map((t, i) => enrichWithDryUp(t, [...themes].sort((a, b) => a.momentumScore - b.momentumScore).slice(0, 8)[i]));

      // Calculate dispersion
      const themePerfs = themes.map(t => t.perf_1d);
      const dispersionScore = calculateDispersion(themePerfs);
      const dispersionLabel = getDispersionShortLabel(dispersionScore);

      // Collect news sentiment for themes
      const themeNewsSentiment = themes
        .map(t => {
          const s = getThemeSentiment(t.themeName);
          if (!s) return null;
          return { name: t.themeName, newsSentiment: s.sentiment, newsScore: s.score };
        })
        .filter(Boolean);

      const payload = {
        date: new Date().toISOString().split("T")[0],
        totalThemes: themes.length,
        requestTimestamp: Date.now(),
        topThemes: top8Enriched,
        bottomThemes: bottom8Enriched,
        outlierThemes,
        dispersionScore,
        dispersionLabel,
        spyPerf1d: spy.perf_1d,
        spyPerf1w: spy.perf_1w,
        spyPerf1m: spy.perf_1m,
        themeNewsSentiment,
      };

      let data: any = null;
      let errorMsg: string | null = null;

      try {
        const result = await supabase.functions.invoke("generate-theme-narrative", {
          body: payload,
        });

        if (result.error) {
          try {
            const ctx = (result.error as any)?.context;
            if (ctx && typeof ctx.json === "function") {
              const body = await ctx.json();
              errorMsg = body?.message || body?.error || "Narrative generation failed";
            } else {
              errorMsg = result.error.message || "Narrative generation failed";
            }
          } catch {
            errorMsg = result.error.message || "Narrative generation failed";
          }
        } else {
          data = result.data;
        }
      } catch (networkErr) {
        errorMsg = "Network error — check your connection and try again";
      }

      if (errorMsg) {
        console.error("Narrative generation failed:", errorMsg);
        toast.error(errorMsg);
        setNarrative(previousNarrative);
        return;
      }

      setNarrative({
        text: data.narrative,
        generatedAt: data.generatedAt,
        themeCount: themes.length,
      });
      setCooldownEnd(Date.now() + COOLDOWN_MS);
    } catch (err) {
      console.error("Narrative generation failed:", err);
      toast.error("Narrative generation failed — check console for details");
      setNarrative(previousNarrative);
    } finally {
      setIsGenerating(false);
    }
  }, [themes, isGenerating, narrative]);

  useEffect(() => {
    if (!hasAutoGenerated.current && !dataLoading && themes.length > 0 && !narrative) {
      hasAutoGenerated.current = true;
      generateNarrative();
    }
  }, [dataLoading, themes.length, narrative, generateNarrative]);

  const scanCacheRaw = localStorage.getItem("ticker_perf_cache");
  let hoursAgo: number | null = null;
  if (scanCacheRaw) {
    try {
      const parsed = JSON.parse(scanCacheRaw);
      hoursAgo = Math.round((Date.now() - new Date(parsed.fetchedAt).getTime()) / 3600000);
    } catch {}
  }
  const isStale = hoursAgo !== null && hoursAgo >= STALE_HOURS;

  return (
    <div className="space-y-4">
      {isStale && (
        <div
          className="flex items-center gap-2 rounded-lg px-4 py-2.5 text-xs"
          style={{
            background: "rgba(245, 166, 35, 0.08)",
            border: "1px solid rgba(245, 166, 35, 0.2)",
          }}
        >
          <AlertTriangle size={14} className="text-[#f5a623] shrink-0" />
          <span className="text-[#f5a623]">
            Narrative based on data from {hoursAgo} hours ago — run a fresh scan for updated insights
          </span>
        </div>
      )}

      <div
        className="relative rounded-lg p-6"
        style={{
          background: "rgba(255,255,255,0.04)",
          border: "1px solid rgba(255,255,255,0.08)",
          backdropFilter: "blur(12px)",
        }}
      >
        <div className="absolute top-4 right-4 flex items-center gap-1.5">
          <span className="relative inline-block h-2 w-2 rounded-full bg-[#00f5c4]">
            <span className="absolute inset-0 rounded-full bg-[#00f5c4] animate-ping opacity-75" />
          </span>
          <span className="text-[10px] font-semibold uppercase tracking-wider text-[#00f5c4]">AI</span>
        </div>

        {isGenerating ? (
          <div className="space-y-3 pr-12">
            <Skeleton className="h-5 w-full" />
            <Skeleton className="h-5 w-full" />
            <Skeleton className="h-5 w-[85%]" />
            <Skeleton className="h-5 w-full" />
            <Skeleton className="h-5 w-[90%]" />
            <Skeleton className="h-5 w-[70%]" />
          </div>
        ) : narrative ? (
          <p
            className="font-['Syne',sans-serif] text-foreground pr-12"
            style={{ fontSize: "15px", lineHeight: 1.8 }}
          >
            {narrative.text}
          </p>
        ) : (
          <p className="text-sm text-muted-foreground pr-12">
            {dataLoading ? "Waiting for theme data…" : "Click Regenerate to generate a market narrative."}
          </p>
        )}

        <div className="mt-4 flex items-center justify-between">
          <span className="text-[10px] text-muted-foreground" style={{ fontFamily: DM_MONO }}>
            {narrative
              ? `Generated ${new Date(narrative.generatedAt).toLocaleTimeString()} · based on ${narrative.themeCount} themes`
              : ""}
          </span>
          <button
            onClick={generateNarrative}
            disabled={isGenerating || isCoolingDown || dataLoading || themes.length === 0}
            className="flex items-center gap-1.5 rounded-md border border-[#00f5c4]/30 bg-[#00f5c4]/10 px-3 py-1.5 text-xs font-medium text-[#00f5c4] transition-colors hover:bg-[#00f5c4]/20 disabled:opacity-40 disabled:cursor-not-allowed"
          >
            <RefreshCw size={12} className={isGenerating ? "animate-spin" : ""} />
            {isGenerating
              ? "Generating…"
              : isCoolingDown
              ? `Wait ${cooldownSecs}s`
              : "Regenerate"}
          </button>
        </div>
      </div>

      <WeeklyReportsSection />

      {/* Volume Dry-Up section */}
      <VolumeDryUpSection themes={dryUpThemes} />

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        {dataLoading ? (
          <>
            <div className="rounded-lg p-4" style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)" }}>
              {Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-6 w-full mb-2" />)}
            </div>
            <div className="rounded-lg p-4" style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)" }}>
              {Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-6 w-full mb-2" />)}
            </div>
          </>
        ) : (
          <>
            <TopBottomCard title="Top 5 — Strongest Momentum" themes={top5} color="teal" />
            <TopBottomCard title="Bottom 5 — Weakest Momentum" themes={bottom5} color="amber" />
          </>
        )}
      </div>

      {/* News Sentiment Overview */}
      {(() => {
        const themesWithSentiment = Object.entries(aiSummaries)
          .filter(([, v]) => v.sentiment)
          .map(([name, v]) => ({ name, sentiment: v.sentiment! }))
          .sort((a, b) => b.sentiment.score - a.sentiment.score);

        if (themesWithSentiment.length === 0) return null;

        return (
          <div
            className="rounded-lg p-4"
            style={{
              background: "rgba(255,255,255,0.04)",
              border: "1px solid rgba(255,255,255,0.08)",
              backdropFilter: "blur(12px)",
            }}
          >
            <h4 className="font-['Syne',sans-serif] text-xs font-semibold uppercase tracking-widest text-primary mb-3 flex items-center gap-2">
              <Newspaper size={14} /> News Sentiment Overview
            </h4>
            <div className="flex flex-wrap gap-1.5">
              {themesWithSentiment.map(({ name, sentiment }) => {
                const config = {
                  bullish: { emoji: "📈", bg: "bg-primary/10", border: "border-primary/20", text: "text-primary" },
                  bearish: { emoji: "📉", bg: "bg-destructive/10", border: "border-destructive/20", text: "text-destructive" },
                  mixed: { emoji: "⚖️", bg: "bg-[#f5a623]/10", border: "border-[#f5a623]/20", text: "text-[#f5a623]" },
                  neutral: { emoji: "📋", bg: "bg-secondary/40", border: "border-border", text: "text-muted-foreground" },
                }[sentiment.sentiment];
                return (
                  <button
                    key={name}
                    onClick={() => onOpenNewsPanel?.(name)}
                    className={`inline-flex items-center gap-1 rounded-md ${config.bg} border ${config.border} px-2 py-1 text-[10px] font-medium ${config.text} transition-colors hover:opacity-80 cursor-pointer`}
                  >
                    {config.emoji} {name}
                    <span className="ml-0.5 opacity-70" style={{ fontFamily: DM_MONO }}>{sentiment.score}</span>
                  </button>
                );
              })}
            </div>
          </div>
        );
      })()}

      {/* Market News Section */}
      {marketNews.length > 0 && (
        <div
          className="rounded-lg p-4"
          style={{
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.08)",
            backdropFilter: "blur(12px)",
          }}
        >
          <h4 className="font-['Syne',sans-serif] text-xs font-semibold uppercase tracking-widest text-primary mb-3 flex items-center gap-2">
            <Newspaper size={14} /> Market News
          </h4>
          <div className="space-y-1.5 max-h-[300px] overflow-y-auto">
            {marketNews.slice(0, 10).map((a, i) => (
              <a
                key={i}
                href={a.url}
                target="_blank"
                rel="noopener noreferrer"
                className="group flex items-start gap-2 rounded-md p-2 transition-colors hover:bg-accent/50"
              >
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-medium text-foreground leading-snug line-clamp-2 group-hover:text-primary transition-colors">
                    {a.headline}
                  </p>
                  <div className="mt-0.5 flex items-center gap-2 text-[10px] text-muted-foreground">
                    {a.source && <span>{a.source}</span>}
                    {a.published_at && (
                      <span>· {(() => {
                        const diff = Date.now() - new Date(a.published_at).getTime();
                        const hrs = Math.floor(diff / 3600000);
                        return hrs < 24 ? `${hrs}h ago` : `${Math.floor(hrs / 24)}d ago`;
                      })()}</span>
                    )}
                  </div>
                </div>
                <ExternalLink size={10} className="shrink-0 mt-1 text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity" />
              </a>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
