import { useState, useEffect, useRef, useCallback } from "react";
import { ThemeIntelData } from "@/hooks/useThemeIntelligence";
import { Skeleton } from "@/components/ui/skeleton";
import { RefreshCw, AlertTriangle } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

const DM_MONO = "'DM Mono', monospace";
const COOLDOWN_MS = 30_000;
const STALE_HOURS = 4;

interface NarrativeState {
  text: string;
  generatedAt: string;
  themeCount: number;
}

function TopBottomCard({
  title,
  themes,
  color,
}: {
  title: string;
  themes: ThemeIntelData[];
  color: "teal" | "amber";
}) {
  const accent = color === "teal" ? "#00f5c4" : "#f5a623";
  return (
    <div
      className="rounded-lg p-4"
      style={{
        background: "rgba(255,255,255,0.04)",
        border: "1px solid rgba(255,255,255,0.08)",
        backdropFilter: "blur(12px)",
      }}
    >
      <h4
        className="font-['Syne',sans-serif] text-xs font-semibold uppercase tracking-widest mb-3"
        style={{ color: accent }}
      >
        {title}
      </h4>
      <div className="space-y-2.5">
        {themes.map((t, i) => (
          <div key={t.themeId} className="flex items-center gap-3">
            <span
              className="w-5 text-right text-xs text-muted-foreground"
              style={{ fontFamily: DM_MONO }}
            >
              {i + 1}
            </span>
            <div className="flex-1 min-w-0">
              <div className="flex items-center justify-between gap-2">
                <span className="font-['Syne',sans-serif] text-[13px] font-medium text-foreground truncate">
                  {t.themeName}
                </span>
                <span
                  className={`shrink-0 text-xs ${t.perf_1d >= 0 ? "text-[#00f5c4]" : "text-[#f5a623]"}`}
                  style={{ fontFamily: DM_MONO }}
                >
                  {t.perf_1d >= 0 ? "+" : ""}
                  {t.perf_1d.toFixed(2)}%
                </span>
              </div>
              <div className="mt-1 h-1 w-full overflow-hidden rounded-full bg-[rgba(255,255,255,0.06)]">
                <div
                  className="h-full rounded-full transition-all duration-700"
                  style={{
                    width: `${t.momentumScore}%`,
                    backgroundColor: accent,
                    opacity: 0.7,
                  }}
                />
              </div>
            </div>
            <span
              className="w-7 text-right text-[10px] text-muted-foreground"
              style={{ fontFamily: DM_MONO }}
            >
              {t.momentumScore}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

export default function InsightsTab({
  themes,
  accelerating,
  fading,
  isLoading: dataLoading,
}: {
  themes: ThemeIntelData[];
  accelerating: ThemeIntelData[];
  fading: ThemeIntelData[];
  isLoading: boolean;
}) {
  const [narrative, setNarrative] = useState<NarrativeState | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [cooldownEnd, setCooldownEnd] = useState(0);
  const [now, setNow] = useState(Date.now());
  const hasAutoGenerated = useRef(false);

  // Tick every second for cooldown countdown
  useEffect(() => {
    const id = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(id);
  }, []);

  const isCoolingDown = now < cooldownEnd;
  const cooldownSecs = Math.ceil((cooldownEnd - now) / 1000);

  const top5 = themes.slice(0, 5);
  const bottom5 = [...themes].sort((a, b) => a.momentumScore - b.momentumScore).slice(0, 5);

  const generateNarrative = useCallback(async () => {
    if (themes.length === 0 || isGenerating) return;

    setIsGenerating(true);
    try {
      const payload = {
        topThemes: top5.map(t => ({
          name: t.themeName,
          score: t.momentumScore,
          perf_1d: t.perf_1d,
          perf_1w: t.perf_1w,
          perf_1m: t.perf_1m,
        })),
        bottomThemes: bottom5.map(t => ({
          name: t.themeName,
          score: t.momentumScore,
          perf_1d: t.perf_1d,
          perf_1w: t.perf_1w,
          perf_1m: t.perf_1m,
        })),
        accelerating: accelerating.slice(0, 5).map(t => t.themeName),
        fading: fading.slice(0, 5).map(t => t.themeName),
        date: new Date().toISOString().split("T")[0],
        totalThemes: themes.length,
      };

      const { data, error } = await supabase.functions.invoke("generate-theme-narrative", {
        body: payload,
      });

      if (error) throw error;

      setNarrative({
        text: data.narrative,
        generatedAt: data.generatedAt,
        themeCount: themes.length,
      });
      setCooldownEnd(Date.now() + COOLDOWN_MS);
    } catch (err) {
      console.error("Narrative generation failed:", err);
    } finally {
      setIsGenerating(false);
    }
  }, [themes, top5, bottom5, accelerating, fading, isGenerating]);

  // Auto-generate on first load when data is ready
  useEffect(() => {
    if (!hasAutoGenerated.current && !dataLoading && themes.length > 0 && !narrative) {
      hasAutoGenerated.current = true;
      generateNarrative();
    }
  }, [dataLoading, themes.length, narrative, generateNarrative]);

  // Check data staleness
  const scanCacheRaw = localStorage.getItem("ticker_perf_cache");
  let hoursAgo: number | null = null;
  if (scanCacheRaw) {
    try {
      const parsed = JSON.parse(scanCacheRaw);
      hoursAgo = Math.round((Date.now() - new Date(parsed.fetchedAt).getTime()) / 3600000);
    } catch {}
  }
  const isStale = hoursAgo !== null && hoursAgo >= STALE_HOURS;

  return (
    <div className="space-y-4">
      {/* Staleness warning */}
      {isStale && (
        <div
          className="flex items-center gap-2 rounded-lg px-4 py-2.5 text-xs"
          style={{
            background: "rgba(245, 166, 35, 0.08)",
            border: "1px solid rgba(245, 166, 35, 0.2)",
          }}
        >
          <AlertTriangle size={14} className="text-[#f5a623] shrink-0" />
          <span className="text-[#f5a623]">
            Narrative based on data from {hoursAgo} hours ago — run a fresh scan for updated insights
          </span>
        </div>
      )}

      {/* Narrative card */}
      <div
        className="relative rounded-lg p-6"
        style={{
          background: "rgba(255,255,255,0.04)",
          border: "1px solid rgba(255,255,255,0.08)",
          backdropFilter: "blur(12px)",
        }}
      >
        {/* Pulsing AI badge */}
        <div className="absolute top-4 right-4 flex items-center gap-1.5">
          <span
            className="relative inline-block h-2 w-2 rounded-full bg-[#00f5c4]"
          >
            <span className="absolute inset-0 rounded-full bg-[#00f5c4] animate-ping opacity-75" />
          </span>
          <span className="text-[10px] font-semibold uppercase tracking-wider text-[#00f5c4]">
            AI
          </span>
        </div>

        {/* Narrative text */}
        {isGenerating ? (
          <div className="space-y-3 pr-12">
            <Skeleton className="h-5 w-full" />
            <Skeleton className="h-5 w-full" />
            <Skeleton className="h-5 w-[85%]" />
            <Skeleton className="h-5 w-[70%]" />
          </div>
        ) : narrative ? (
          <p
            className="font-['Syne',sans-serif] text-[16px] leading-[1.75] text-foreground pr-12"
          >
            {narrative.text}
          </p>
        ) : (
          <p className="text-sm text-muted-foreground pr-12">
            {dataLoading ? "Waiting for theme data…" : "Click Regenerate to generate a market narrative."}
          </p>
        )}

        {/* Footer */}
        <div className="mt-4 flex items-center justify-between">
          <span className="text-[10px] text-muted-foreground" style={{ fontFamily: DM_MONO }}>
            {narrative
              ? `Generated ${new Date(narrative.generatedAt).toLocaleTimeString()} · based on ${narrative.themeCount} themes`
              : ""}
          </span>
          <button
            onClick={generateNarrative}
            disabled={isGenerating || isCoolingDown || dataLoading || themes.length === 0}
            className="flex items-center gap-1.5 rounded-md border border-[#00f5c4]/30 bg-[#00f5c4]/10 px-3 py-1.5 text-xs font-medium text-[#00f5c4] transition-colors hover:bg-[#00f5c4]/20 disabled:opacity-40 disabled:cursor-not-allowed"
          >
            <RefreshCw size={12} className={isGenerating ? "animate-spin" : ""} />
            {isGenerating
              ? "Generating…"
              : isCoolingDown
              ? `Wait ${cooldownSecs}s`
              : "Regenerate"}
          </button>
        </div>
      </div>

      {/* Top 5 / Bottom 5 */}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        {dataLoading ? (
          <>
            <div className="rounded-lg p-4" style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)" }}>
              {Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-6 w-full mb-2" />)}
            </div>
            <div className="rounded-lg p-4" style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)" }}>
              {Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-6 w-full mb-2" />)}
            </div>
          </>
        ) : (
          <>
            <TopBottomCard title="Top 5 — Strongest Momentum" themes={top5} color="teal" />
            <TopBottomCard title="Bottom 5 — Weakest Momentum" themes={bottom5} color="amber" />
          </>
        )}
      </div>
    </div>
  );
}
